"""E2E intent-routing tests for ovos-skill-number-facts.

Auto-generated by tools/gen_ovoscope_tests.py
Run: pytest test/end2end/ -v
"""
from unittest import TestCase

from ovos_bus_client.message import Message
from ovos_bus_client.session import Session
from ovoscope import End2EndTest, get_minicroft

SKILL_ID = "ovos-skill-number-facts.openvoiceos"
LANG = "en-US"


class _IntentRoutingMixin:
    """Shared MiniCroft setup."""

    @classmethod
    def setUpClass(cls):
        cls.minicroft = get_minicroft([SKILL_ID])

    @classmethod
    def tearDownClass(cls):
        if getattr(cls, 'minicroft', None):
            cls.minicroft.stop()


    def _assert_adapt(self, utterance: str, intent_label: str = ''):
        intent_msg_type = f"{SKILL_ID}:{intent_label}" if intent_label else None
        session = Session(f"e2e-en_us-adapt-{hash(utterance)}")
        session.lang = LANG
        session.pipeline = [
            "ovos-adapt-pipeline-plugin-high",
            "ovos-adapt-pipeline-plugin-medium",
            "ovos-adapt-pipeline-plugin-low",
        ]
        message = Message(
            "recognizer_loop:utterance",
            {"utterances": [utterance], "lang": LANG},
            {"session": session.serialize()},
        )
        activation_points = [intent_msg_type] if intent_msg_type else []
        expected = [
            message,
            Message(f"{SKILL_ID}.activate", {}, {"skill_id": SKILL_ID}),
            Message("mycroft.skill.handler.start", {}, {"skill_id": SKILL_ID}),
            Message("mycroft.skill.handler.complete", {}, {"skill_id": SKILL_ID}),
            Message("ovos.utterance.handled", {}, {"skill_id": SKILL_ID}),
        ]
        if intent_msg_type:
            expected.insert(2, Message(intent_msg_type, {}, {"skill_id": SKILL_ID}))
        test = End2EndTest(
            minicroft=self.minicroft,
            skill_ids=[SKILL_ID],
            eof_msgs=["ovos.utterance.handled"],
            flip_points=["recognizer_loop:utterance"],
            source_message=message,
            activation_points=activation_points,
            test_msg_context=False,
            test_message_number=False,
            ignore_messages=["speak", "mycroft.audio.play_sound"],
            expected_messages=expected,
        )
        test.execute(timeout=30)


class TestAdapt1_Number_trivia(_IntentRoutingMixin, TestCase):
    """Adapt intent: number_trivia"""
    def test_curiosity_number(self):
        self._assert_adapt(r"curiosity number", r"number_trivia")

    def test_curiosity_number_aleatory(self):
        self._assert_adapt(r"curiosity number aleatory", r"number_trivia")

    def test_curiosity_number_api(self):
        self._assert_adapt(r"curiosity number numbers api", r"number_trivia")

class TestAdapt2_Math_trivia(_IntentRoutingMixin, TestCase):
    """Adapt intent: math_trivia"""
    def test_curiosity_math(self):
        self._assert_adapt(r"curiosity math", r"math_trivia")

    def test_curiosity_math_aleatory(self):
        self._assert_adapt(r"curiosity math aleatory", r"math_trivia")

    def test_curiosity_math_api(self):
        self._assert_adapt(r"curiosity math numbers api", r"math_trivia")

class TestAdapt3_Date_trivia(_IntentRoutingMixin, TestCase):
    """Adapt intent: date_trivia"""
    def test_curiosity_april(self):
        self._assert_adapt(r"curiosity april", r"date_trivia")

    def test_curiosity_april_aleatory(self):
        self._assert_adapt(r"curiosity april aleatory", r"date_trivia")

    def test_curiosity_april_api(self):
        self._assert_adapt(r"curiosity april numbers api", r"date_trivia")

class TestAdapt4_Year_trivia(_IntentRoutingMixin, TestCase):
    """Adapt intent: year_trivia"""
    def test_curiosity_year(self):
        self._assert_adapt(r"curiosity year", r"year_trivia")

    def test_curiosity_year_aleatory(self):
        self._assert_adapt(r"curiosity year aleatory", r"year_trivia")

    def test_curiosity_year_api(self):
        self._assert_adapt(r"curiosity year numbers api", r"year_trivia")
